[package]
name = "xtask"
version = "0.1.0"
edition = "2024"
default-run = "xtask"

[dependencies]
anyhow.workspace = true
bootloader.workspace = true
clap.workspace = true
serde_json.workspace = true
fatfs = "0.3"
